Imaginea/fontli

app/models/photo.rb, config/deploy.rb, lib/tasks/photos.rake
Also, update likes_count of photos with negative value
=> A capistrano task to execute rake tasks and other code modification related to un-liking a photo

Gemfile, Gemfile.lock, config/routes.rb
LoadError: cannot load such file -- net/ssh.
https://github.com/fog/fog/issues/3765
=> Update fog version to 1.38.0

app/views/admin/users.html.erb
Refs: https://gitlab.pramati.com/Fontli/Backend/issues/13
=> Added a delete confirmation dialog for user deletion from admin panel

app/mailers/app_mailer.rb, app/models/photo.rb, app/views/app_mailer/sos_requested_mail.text.erb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb
Refs: https://gitlab.pramati.com/Fontli/Fontli/issues/84
=> Send a mail to a selected list when an sos is requested

app/models/photo.rb, config/config.yml
https://gitlab.pramati.com/Fontli/Backend/issues/14
=> Disable filesystem storage of photos for staging

app/controllers/api_base_controller.rb, app/models/api_session.rb, test/controllers/api_actions_controller_test.rb, test/models/api_session_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/2
=> Updated auth_token generation

app/controllers/admin_controller.rb, app/views/admin/_top_nav.html.erb, test/controllers/admin_controller_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/19
=> Backend19: Remove 'Add Photos' submenu from collections menu of admin

app/models/follow.rb, test/controllers/api_actions_controller_test.rb, test/controllers/feeds_controller_test.rb, test/factories/follow.rb, test/models/follow_test.rb, test/models/user_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/18
=> Backend18: Added inverse_of option to follower association of Follow model

app/controllers/api_actions_controller.rb, lib/tasks/photos.rake, test/controllers/api_actions_controller_test.rb
https://gitlab.pramati.com/Fontli/Fontli/issues/132
=> Set font_help as true for requested SoS via add_to_sos api

app/models/photo.rb, test/models/photo_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/23
Note:
The purpose of this change is to allow users see the recently approved sos on the top of sos feeds.
=> Backend23: Sort the sos feeds by approval date

app/controllers/admin_controller.rb, app/views/admin/photos.html.erb, lib/tasks/photos.rake, test/controllers/admin_controller_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/22
=> Backend22: Reset the flags_count once the photo is unflagged

app/controllers/api_actions_controller.rb, app/controllers/api_base_controller.rb, lib/api_helper.rb, test/controllers/api_actions_controller_test.rb
https://gitlab.pramati.com/Fontli/Fontli/issues/150
=> Fontli150: Added an api to return an array of urls of homepage photos

.env, .gitignore, Gemfile, Gemfile.lock, app/controllers/admin_controller.rb, app/controllers/feeds_controller.rb, app/controllers/welcome_controller.rb, app/views/feeds/profile.js.erb, config/deploy/production.rb, config/deploy/staging.rb, config/initializers/secret_token.rb, test/controllers/admin_controller_test.rb, test/controllers/feeds_controller_test.rb, test/test_helper.rb
Resolved Brakeman critical issues and added test cases for the same. Also configured environment to avoid secret data being tracked in version control.
=> Brakemam critical issues fix and resolved random failing test case

app/controllers/api_actions_controller.rb, app/controllers/api_base_controller.rb, lib/api_helper.rb, test/controllers/admin_controller_test.rb, test/controllers/api_actions_controller_test.rb, test/controllers/feeds_controller_test.rb, test/factories/notification.rb, test/mailers/app_mailer_test.rb, test/models/api_session_test.rb, test/models/notification_test.rb, test/models/photo_test.rb, test/models/user_test.rb
https://gitlab.pramati.com/Fontli/Fontli/issues/150
=> Fontli150: Return a random set of homepage photos urls

app/controllers/admin_controller.rb, app/helpers/admin_helper.rb, app/views/admin/_popular_header.html.erb, app/views/admin/_top_nav.html.erb, app/views/admin/collections.html.erb, app/views/admin/index.html.erb, app/views/admin/photos.html.erb, app/views/admin/popular_photos.html.erb, app/views/admin/popular_users.html.erb, app/views/admin/send_push_notifications.html.erb, app/views/admin/top_contributors.html.erb, app/views/admin/users.html.erb, config/routes.rb, test/controllers/admin_controller_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/26
=> Fixed default route warnings

Gemfile, Gemfile.lock, app/controllers/welcome_controller.rb, app/models/photo.rb, app/models/user.rb, app/views/feeds/search.html.erb, app/views/shared/_photo_list.html.erb, app/views/welcome/index.html.erb, test/models/photo_test.rb
Also fixes for rubocop issues for photo,user model
=> Updated moped, bson gem version; fixed Command injection issues

app/models/photo.rb, test/models/photo_test.rb
https://gitlab.pramati.com/Fontli/Fontli/issues/202
=> Fontli202: Allow editing of published photos

app/models/user.rb, test/controllers/api_actions_controller_test.rb
https://gitlab.pramati.com/Fontli/Fontli/issues/207
=> For Fontli #207, changed the email validation message

app/assets/stylesheets/admin.css, app/controllers/admin_controller.rb, app/views/admin/collections.html.erb, config/routes.rb, test/controllers/admin_controller_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/30
=> For #30, allow admin to delete inactive collections

app/controllers/api_base_controller.rb, app/models/font.rb, lib/api_helper.rb, test/controllers/api_actions_controller_test.rb, test/models/font_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/28
Updating coords to coordinates as  it throws exception while parsing data for current app.
=> For #28, Renamed coords to coordinates

app/models/photo.rb, lib/api_helper.rb, test/models/photo_test.rb
https://gitlab.pramati.com/Fontli/Fontli/issues/257
=> For fontli257, Added a property to indicate whether current user is following feed user

app/controllers/api_actions_controller.rb, app/mailers/app_mailer.rb, app/models/collection.rb, app/models/font_tag.rb, app/models/photo.rb, app/views/app_mailer/inactive_collection_creation_mail.html.erb, app/views/app_mailer/inactive_collection_creation_mail.text.erb, test/controllers/api_actions_controller_test.rb, test/mailers/app_mailer_test.rb, test/models/collection_test.rb, test/models/font_tag_test.rb, test/models/photo_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/29
=> For #29, Allow users to add new collections, fix publish_photo api to accept collection and font_tags

app/models/photo.rb, test/models/photo_test.rb
https://gitlab.pramati.com/Fontli/Fontli/issues/243
=> For fontli #243, Assign photo created_at only once

app/assets/stylesheets/admin.css, app/views/collections/edit.html.erb
https://gitlab.pramati.com/Fontli/Backend/issues/32
=> Disable editing of collection name and allow to upload another image for collection

app/controllers/feeds_controller.rb, lib/tasks/photos.rake
https://gitlab.pramati.com/Fontli/Backend/issues/35
=> For #35, Log the backtrace of exception for feed permalink, add a task to reset photos fonts_count

app/assets/javascripts/admin/custom.js, app/assets/stylesheets/admin.css, app/controllers/collections_controller.rb, app/views/collections/edit.html.erb, test/controllers/collections_controller_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/32
=> For #32, Update the photo data of collection cover_photo when a new image is assigned

app/controllers/api_actions_controller.rb, app/models/hash_tag.rb, test/models/hash_tag_test.rb
https://gitlab.pramati.com/Fontli/Fontli/issues/246
=> For fontli #246, retun the photos of hash_tags exactly matching the name

app/assets/javascripts/admin/custom.js, app/assets/javascripts/admin/user.js, app/assets/stylesheets/admin.css, app/controllers/collections_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/admin/_photos.html.erb, app/views/admin/photos.html.erb, app/views/admin/users.html.erb, app/views/collections/index.html.erb, app/views/layouts/admin.html.erb, app/views/users/_photo_modal.html.erb, app/views/users/add_photo.js.erb, app/views/users/show.html.erb, config/routes.rb, test/controllers/users_controller_test.rb, test/models/user_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/37
=> For #37, allow admin to upload images from a user account

lib/api_helper.rb, test/controllers/api_actions_controller_test.rb
https://gitlab.pramati.com/Fontli/Backend/issues/39
=> For #39, Added followers count in user search api
